export { default } from './Icon.svelte';

export const icons = [
  'angle_down_pro',
  'angle_left_pro',
  'angle_up_pro',
  'article',
  'check_pro',
  'credit_card',
  'ebplus_icon',
  'ebplus_sort',
  'envelope',
  'gallery',
  'headphones',
  'headset',
  'lock',
  'medielogin',
  'menu-bars',
  'miteb-regular',
  'miteb-solid',
  'mobil_fone',
  'newspaper',
  'play-circle-light',
  'tag-regular',
  'tag-solid',
  'tags-regular',
  'tags-solid',
  'video',
];
